🔧Use babel-watch to replace nodemon
Because of this issue https://github.com/remy/nodemon/issues/1025
➕babel-wathc
➖nodemon
⚠️It may crash when saving files quickly
(detail:
TypeError: First argument must be file descriptor
https://github.com/kmagiera/babel-watch/blob/0bb38ce492b32ae196574a8b36daa79c5a7f61e5/babel-watch.js#L291)